# report_generator.py
from fpdf import FPDF
import base64

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Movie Success Prediction Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def create_pdf(movie_data, prediction_results):
    pdf = PDFReport()
    pdf.add_page()
    
    # Movie Details
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Movie Details', 0, 1)
    pdf.set_font('Arial', '', 10)
    
    for key, value in movie_data.items():
        pdf.cell(50, 10, f"{key}:", 0, 0)
        pdf.cell(0, 10, f"{value}", 0, 1)
        
    pdf.ln(10)
    
    # Prediction Results
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'AI Analysis Results', 0, 1)
    pdf.set_font('Arial', '', 10)
    
    pdf.cell(50, 10, "Predicted Success:", 0, 0)
    pdf.set_text_color(0, 150, 0)
    pdf.cell(0, 10, f"{prediction_results['success']}", 0, 1)
    pdf.set_text_color(0, 0, 0)
    
    pdf.cell(50, 10, "Est. Collection:", 0, 0)
    pdf.cell(0, 10, f"{prediction_results['collection']}", 0, 1)
    
    pdf.cell(50, 10, "Confidence Score:", 0, 0)
    pdf.cell(0, 10, f"{prediction_results['confidence']}", 0, 1)
    
    pdf.ln(10)
    
    # Insights
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Key Insights', 0, 1)
    pdf.set_font('Arial', '', 10)
    
    pdf.multi_cell(0, 10, f"Director Score: {prediction_results['dir_score']}")
    pdf.multi_cell(0, 10, f"Actor Score: {prediction_results['act_score']}")
    
    pdf.ln(5)
    pdf.set_font('Arial', 'I', 8)
    pdf.cell(0, 10, "Generated by Movie Box Office AI V4", 0, 1)
    
    return pdf.output(dest='S').encode('latin-1')

def get_download_link(pdf_bytes, filename="report.pdf"):
    b64 = base64.b64encode(pdf_bytes).decode()
    return f'<a href="data:application/octet-stream;base64,{b64}" download="{filename}">📥 Download PDF Report</a>'
